import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-admin',
  templateUrl: './admin.component.html',
  styleUrls: ['./admin.component.css']
})
export class AdminComponent implements OnInit {
  activeTab = 'users';
  selectedUser: any = null;

  rolePermissions: Record<string, string[]> = {
    admin: [
      'dashboard', 'program-performance', 'beneficiary-analytics', 'outcomes',
      'reports', 'report-builder', 'data-sources', 'data-quality', 'data-pipeline',
      'ai-assistant', 'ai-insights', 'admin'
    ],
    program_manager: [
      'dashboard', 'program-performance', 'beneficiary-analytics', 'outcomes',
      'reports', 'report-builder', 'ai-assistant', 'ai-insights'
    ],
    me_officer: [
      'dashboard', 'program-performance', 'beneficiary-analytics', 'outcomes',
      'data-quality', 'data-pipeline', 'ai-assistant', 'ai-insights'
    ],
    reporting_officer: [
      'dashboard', 'program-performance', 'beneficiary-analytics', 'outcomes',
      'reports', 'report-builder', 'data-sources', 'data-quality', 'data-pipeline',
      'ai-assistant'
    ],
    leadership: [
      'dashboard', 'program-performance', 'beneficiary-analytics', 'outcomes',
      'reports', 'ai-assistant', 'ai-insights'
    ]
  };

  pageLabels: Record<string, string> = {
    'dashboard': 'Dashboard',
    'program-performance': 'Program Performance',
    'beneficiary-analytics': 'Beneficiary Analytics',
    'outcomes': 'Outcomes & Impact',
    'reports': 'Reports',
    'report-builder': 'Report Builder',
    'data-sources': 'Data Sources',
    'data-quality': 'Data Quality',
    'data-pipeline': 'Data Pipeline',
    'ai-assistant': 'AI Assistant',
    'ai-insights': 'AI Insights',
    'admin': 'Users & Roles'
  };

  users: any[] = [];
  auditLogs: any[] = [];
  selectedCategory = 'All';
  categories = ['All', 'Report', 'Data Quality', 'Pipeline', 'Workflow', 'Security', 'Settings'];

  settings: any = {
    orgName: 'KPC Inuka Foundation',
    reportingFrequency: 'quarterly',
    emailNotifications: true,
    defaultPeriod: 'Q3 2026',
    autoGenerateDonorReport: true,
    scheduledDeliveryDay: 'Last Friday of Quarter',
    escalationReminderDays: 3
  };
  settingsSaved = false;
  settingsSaving = false;
  periods: any[] = [];

  notifications: any[] = [];
  unreadNotifsCount = 0;

  constructor(private api: ApiService) {}

  ngOnInit(): void {
    this.loadSettings();
    this.loadUsers();
    this.loadAuditLogs();
    this.loadNotifications();
    this.api.getPeriods().subscribe({
      next: (data: any) => { this.periods = data.items || (Array.isArray(data) ? data : []); }
    });
  }

  loadNotifications(): void {
    this.api.getNotifications('admin').subscribe({
      next: (res: any) => {
        this.notifications = res.notifications || [];
        this.unreadNotifsCount = res.unread_count || 0;
      }
    });
  }

  markRead(n: any): void {
    n.read = true;
    n.is_read = true;
    this.api.markNotificationRead(n.id).subscribe({
      next: () => {
        this.unreadNotifsCount = Math.max(0, this.unreadNotifsCount - 1);
      }
    });
  }

  clearAllNotifs(): void {
    this.api.clearAllNotifications('admin').subscribe({
      next: () => {
        this.notifications.forEach(n => { n.read = true; n.is_read = true; });
        this.unreadNotifsCount = 0;
      }
    });
  }

  loadSettings(): void {
    this.api.getSettings().subscribe({
      next: (data) => { if (data) this.settings = { ...this.settings, ...data }; }
    });
  }

  loadUsers(): void {
    this.api.getAdminUsers().subscribe({
      next: (data) => {
        this.users = (data || []).map((u: any) => ({
          ...u,
          roleKey: u.role,
          role: u.role_label || u.role
        }));
      },
      error: () => {
        // Fallback default users
        this.users = [
          { id: 1, name: 'Program Administrator', email: 'admin@inukafoundation.org', role: 'Administrator', roleKey: 'admin', status: 'Active', lastActive: '2026-08-20' },
          { id: 2, name: 'Grace Wanjiku', email: 'grace.w@inukafoundation.org', role: 'Program Manager', roleKey: 'program_manager', status: 'Active', lastActive: '2026-08-19' },
          { id: 3, name: 'James Otieno', email: 'james.o@inukafoundation.org', role: 'M&E Officer', roleKey: 'me_officer', status: 'Active', lastActive: '2026-08-20' },
          { id: 4, name: 'Amina Hassan', email: 'amina.h@inukafoundation.org', role: 'Reporting Officer', roleKey: 'reporting_officer', status: 'Active', lastActive: '2026-08-18' },
          { id: 5, name: 'David Mwangi', email: 'david.m@inukafoundation.org', role: 'Leadership', roleKey: 'leadership', status: 'Active', lastActive: '2026-08-15' },
          { id: 6, name: 'Sarah Njeri', email: 'sarah.n@inukafoundation.org', role: 'Program Manager', roleKey: 'program_manager', status: 'Inactive', lastActive: '2026-07-01' }
        ];
      }
    });
  }

  loadAuditLogs(): void {
    this.api.getAuditLogs().subscribe({
      next: (data) => { this.auditLogs = data || []; },
      error: () => {}
    });
  }

  toggleUserStatus(user: any): void {
    const newStatus = user.status === 'Active' ? 'Inactive' : 'Active';
    user.status = newStatus;
    this.api.updateAdminUser(user.id, { status: newStatus }).subscribe({
      next: () => { this.loadAuditLogs(); },
      error: () => {}
    });
  }

  changeUserRole(user: any, newRole: string): void {
    user.roleKey = newRole;
    this.api.updateAdminUser(user.id, { role: newRole }).subscribe({
      next: () => {
        this.loadUsers();
        this.loadAuditLogs();
      }
    });
  }

  saveSettings(): void {
    this.settingsSaving = true;
    this.settingsSaved = false;
    this.api.updateSettings(this.settings).subscribe({
      next: (data) => {
        this.settings = data;
        this.settingsSaving = false;
        this.settingsSaved = true;
        this.loadAuditLogs();
        setTimeout(() => this.settingsSaved = false, 3000);
      },
      error: () => { this.settingsSaving = false; }
    });
  }

  getUserPermissions(user: any): string[] {
    return this.rolePermissions[user.roleKey] || [];
  }

  getPermissionCount(user: any): number {
    return this.getUserPermissions(user).length;
  }

  viewPermissions(user: any): void {
    this.selectedUser = this.selectedUser?.id === user.id ? null : user;
  }

  getPageLabel(page: string): string {
    return this.pageLabels[page] || page;
  }

  getAllPages(): string[] {
    return Object.keys(this.pageLabels);
  }

  get filteredAuditLogs(): any[] {
    if (this.selectedCategory === 'All') return this.auditLogs;
    return this.auditLogs.filter(l => l.category === this.selectedCategory || l.action.toLowerCase().includes(this.selectedCategory.toLowerCase()));
  }
}

