"""PDF Export service for donor reports using FPDF2."""

import os
import re
from datetime import datetime, timezone
from typing import Optional

from fpdf import FPDF

from src.config import REPORT_EXPORT_DIR


SECTION_TITLES = {
    "executive_summary": "Executive Summary",
    "programmatic_progress": "Programmatic Progress",
    "financial_utilization": "Financial Utilization",
    "operational_challenges": "Operational Challenges",
    "impact_narratives": "Impact Narratives",
    "next_quarter_outlook": "Next Quarter Outlook",
}


def _sanitize_text(text: str) -> str:
    """Remove non-latin-1 characters for FPDF compatibility."""
    replacements = {
        '\u2013': '-', '\u2014': '--', '\u2018': "'", '\u2019': "'",
        '\u201c': '"', '\u201d': '"', '\u2026': '...', '\u2022': '*',
        '\u00a0': ' ', '\u2010': '-', '\u2011': '-', '\u2012': '-',
        '\u2015': '--', '\u2017': '"', '\u2019': "'", '\u2032': "'",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text.encode('latin-1', errors='replace').decode('latin-1')


class DonorReportPDF(FPDF):
    def __init__(self, report_title: str, donor_name: str = ""):
        super().__init__()
        self.report_title = report_title
        self.donor_name = donor_name
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(26, 35, 126)
        self.cell(0, 8, _sanitize_text(self.report_title[:60]), align="L")
        if self.donor_name:
            self.set_text_color(100, 100, 100)
            self.cell(0, 8, _sanitize_text(f"Donor: {self.donor_name}"), align="R", new_x="LMARGIN", new_y="NEXT")
        else:
            self.cell(0, 8, "", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(26, 35, 126)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Generated by Insightful System", align="C")

    def add_cover_page(self, workflow_status: str, created_at: Optional[str] = None):
        self.add_page()
        self.ln(40)

        self.set_font("Helvetica", "B", 28)
        self.set_text_color(26, 35, 126)
        self.cell(0, 15, _sanitize_text(self.report_title), align="C", new_x="LMARGIN", new_y="NEXT")

        if self.donor_name:
            self.set_font("Helvetica", "", 18)
            self.set_text_color(66, 66, 66)
            self.cell(0, 12, _sanitize_text(f"Prepared for: {self.donor_name}"), align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(10)
        self.set_draw_color(26, 35, 126)
        self.set_line_width(0.5)
        self.line(60, self.get_y(), 150, self.get_y())
        self.ln(15)

        self.set_font("Helvetica", "", 12)
        self.set_text_color(100, 100, 100)

        created = created_at or datetime.now(timezone.utc).strftime("%B %d, %Y")
        self.cell(0, 8, f"Date: {created}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 8, f"Status: {workflow_status.replace('_', ' ').title()}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 8, f"Organization: Inuka Foundation", align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(30)
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, "This document was generated by the Insightful System", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 8, "Intelligent Automated Reporting & Admin Workflow System", align="C", new_x="LMARGIN", new_y="NEXT")

    def add_section(self, section_id: str, content: str):
        title = SECTION_TITLES.get(section_id, section_id.replace("_", " ").title())

        self.add_page()
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(26, 35, 126)
        self.cell(0, 12, _sanitize_text(title), new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(26, 35, 126)
        self.line(10, self.get_y(), 80, self.get_y())
        self.ln(8)

        self.set_font("Helvetica", "", 11)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 6, _sanitize_text(content))
        self.ln(5)

    def add_table(self, headers: list[str], rows: list[list[str]], col_widths: Optional[list[float]] = None):
        if not col_widths:
            col_widths = [190 / len(headers)] * len(headers)

        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(26, 35, 126)
        self.set_text_color(255, 255, 255)
        for i, header in enumerate(headers):
            self.cell(col_widths[i], 8, _sanitize_text(header), border=1, fill=True, align="C")
        self.ln()

        self.set_font("Helvetica", "", 9)
        self.set_text_color(51, 51, 51)
        fill = False
        for row in rows:
            if fill:
                self.set_fill_color(240, 240, 250)
            else:
                self.set_fill_color(255, 255, 255)
            for i, cell in enumerate(row):
                self.cell(col_widths[i], 7, _sanitize_text(str(cell)[:50]), border=1, fill=True)
            self.ln()
            fill = not fill


def generate_report_pdf(
    report_id: int,
    title: str,
    donor_name: Optional[str],
    workflow_status: str,
    ai_content: dict,
    created_at: Optional[str] = None,
) -> str:
    pdf = DonorReportPDF(title, donor_name or "")
    pdf.alias_nb_pages()
    pdf.add_cover_page(workflow_status, created_at)

    for section_id in [
        "executive_summary",
        "programmatic_progress",
        "financial_utilization",
        "operational_challenges",
        "impact_narratives",
        "next_quarter_outlook",
    ]:
        section_data = ai_content.get(section_id, {})
        content = section_data.get("content", "") if isinstance(section_data, dict) else str(section_data)
        if content:
            pdf.add_section(section_id, content)

            data_summary = section_data.get("data_summary", {}) if isinstance(section_data, dict) else {}
            if section_id == "programmatic_progress" and data_summary.get("metrics"):
                metrics = data_summary["metrics"]
                if metrics:
                    pdf.add_table(
                        ["KPI", "Category", "Target", "Actual", "Attainment"],
                        [
                            [
                                str(m.get("name", ""))[:30],
                                str(m.get("category", ""))[:15],
                                str(m.get("target", 0)),
                                str(m.get("actual", 0)),
                                f"{m.get('attainment', 0)}%",
                            ]
                            for m in metrics[:10]
                        ],
                        [55, 35, 30, 30, 30],
                    )
                    pdf.ln(5)

            elif section_id == "financial_utilization" and data_summary.get("items"):
                items = data_summary["items"]
                if items:
                    pdf.add_table(
                        ["Line Item", "Category", "Budget", "Spend", "Burn Rate"],
                        [
                            [
                                str(i.get("line_item", ""))[:30],
                                str(i.get("category", ""))[:15],
                                f"${i.get('budget', 0):,.0f}",
                                f"${i.get('spend', 0):,.0f}",
                                f"{i.get('burn_rate', 0)}%",
                            ]
                            for i in items[:10]
                        ],
                        [55, 35, 30, 30, 30],
                    )
                    pdf.ln(5)

    os.makedirs(REPORT_EXPORT_DIR, exist_ok=True)
    filename = f"donor_report_{report_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(REPORT_EXPORT_DIR, filename)
    pdf.output(filepath)

    return filepath
