"""Admin settings & workflows API — persists to JSON files with notifications system."""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

from ..config import PROJECT_DIR
from ..auth.service import USERS, ROLE_LABELS

router = APIRouter(prefix="/api", tags=["admin"])

SETTINGS_FILE = PROJECT_DIR / "data" / "settings.json"
AUDIT_FILE = PROJECT_DIR / "data" / "audit_logs.json"
NOTIFICATIONS_FILE = PROJECT_DIR / "data" / "notifications.json"

DEFAULT_SETTINGS = {
    "orgName": "KPC Inuka Foundation",
    "reportingFrequency": "quarterly",
    "emailNotifications": True,
    "defaultPeriod": "Q3 2026",
    "autoGenerateDonorReport": True,
    "scheduledDeliveryDay": "Last Friday of Quarter",
    "escalationReminderDays": 3,
}

DEFAULT_AUDIT_LOGS = [
    {"id": 1, "timestamp": "2026-08-20 14:32", "user": "Program Administrator", "action": "Generated Executive Report", "details": "Q3 2026 Executive Summary", "category": "Report"},
    {"id": 2, "timestamp": "2026-08-20 10:15", "user": "James Otieno (M&E)", "action": "Resolved Data Quality Issues", "details": "Auto-standardized 142 phone number formats", "category": "Data Quality"},
    {"id": 3, "timestamp": "2026-08-19 16:45", "user": "Grace Wanjiku (PM)", "action": "Approved Pillar Performance", "details": "Scholarship Performance Q3 2026 signed off", "category": "Workflow"},
    {"id": 4, "timestamp": "2026-08-19 09:20", "user": "Amina Hassan (Reporting)", "action": "Exported Donor Report", "details": "Quarterly Donor Update Q2 2026 (.xlsx)", "category": "Report"},
    {"id": 5, "timestamp": "2026-08-18 11:00", "user": "Program Administrator", "action": "Ran Real-Time Data Pipeline", "details": "Full 4-pillar ETL sync completed (73k+ records)", "category": "Pipeline"},
    {"id": 6, "timestamp": "2026-08-15 14:30", "user": "David Mwangi (Director)", "action": "Reviewed Executive Dashboard", "details": "Q3 2026 High-level Impact KPI review", "category": "Governance"},
]

DEFAULT_NOTIFICATIONS = [
    {
        "id": 1,
        "recipient_role": "program_manager",
        "title": "New Report Awaiting Your Review",
        "message": "Admin submitted 'Q3 2026 Inuka Cross-Pillar Donor Impact Report' for review.",
        "report_id": 1,
        "type": "report_submitted",
        "created_at": "2026-08-25T14:30:00Z",
        "read": False
    },
    {
        "id": 2,
        "recipient_role": "admin",
        "title": "Report Approved by Manager",
        "message": "Manager Grace Wanjiku has approved 'Q2 2026 Executive Summary'.",
        "report_id": 2,
        "type": "report_approved",
        "created_at": "2026-08-25T12:15:00Z",
        "read": False
    }
]


def _load_settings() -> dict:
    if SETTINGS_FILE.exists():
        try:
            return json.loads(SETTINGS_FILE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return DEFAULT_SETTINGS.copy()


def _save_settings(data: dict) -> None:
    SETTINGS_FILE.parent.mkdir(parents=True, exist_ok=True)
    SETTINGS_FILE.write_text(json.dumps(data, indent=2), encoding="utf-8")


def _load_audit_logs() -> list[dict]:
    if AUDIT_FILE.exists():
        try:
            return json.loads(AUDIT_FILE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return DEFAULT_AUDIT_LOGS.copy()


def _save_audit_logs(logs: list[dict]) -> None:
    AUDIT_FILE.parent.mkdir(parents=True, exist_ok=True)
    AUDIT_FILE.write_text(json.dumps(logs, indent=2), encoding="utf-8")


def _load_notifications() -> list[dict]:
    if NOTIFICATIONS_FILE.exists():
        try:
            return json.loads(NOTIFICATIONS_FILE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return DEFAULT_NOTIFICATIONS.copy()


def _save_notifications(notifications: list[dict]) -> None:
    NOTIFICATIONS_FILE.parent.mkdir(parents=True, exist_ok=True)
    NOTIFICATIONS_FILE.write_text(json.dumps(notifications, indent=2), encoding="utf-8")


def create_notification(recipient_role: str, title: str, message: str, report_id: Optional[int] = None, notif_type: str = "general") -> dict:
    """Create a persistent notification for target role(s)."""
    notifications = _load_notifications()
    new_notif = {
        "id": len(notifications) + 1,
        "recipient_role": recipient_role,
        "title": title,
        "message": message,
        "report_id": report_id,
        "type": notif_type,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "read": False
    }
    notifications.insert(0, new_notif)
    _save_notifications(notifications[:100])
    return new_notif


class SettingsUpdate(BaseModel):
    orgName: Optional[str] = None
    reportingFrequency: Optional[str] = None
    emailNotifications: Optional[bool] = None
    defaultPeriod: Optional[str] = None
    autoGenerateDonorReport: Optional[bool] = None
    scheduledDeliveryDay: Optional[str] = None
    escalationReminderDays: Optional[int] = None


class UserStatusUpdate(BaseModel):
    status: Optional[str] = None
    role: Optional[str] = None


class AuditLogCreate(BaseModel):
    user: str
    action: str
    details: str
    category: Optional[str] = "General"


@router.get("/admin/settings")
def get_settings():
    return _load_settings()


@router.put("/admin/settings")
def update_settings(body: SettingsUpdate):
    current = _load_settings()
    updates = body.model_dump(exclude_unset=True)
    current.update(updates)
    _save_settings(current)
    
    logs = _load_audit_logs()
    logs.insert(0, {
        "id": len(logs) + 1,
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M"),
        "user": "Program Administrator",
        "action": "Updated System Settings",
        "details": f"Updated settings: {list(updates.keys())}",
        "category": "Settings",
    })
    _save_audit_logs(logs[:50])
    return current


@router.get("/admin/users")
def get_admin_users():
    return [
        {
            "id": u["id"],
            "name": u["name"],
            "email": u["email"],
            "role": u["role"],
            "role_label": ROLE_LABELS.get(u["role"], u["role"]),
            "status": u.get("status", "active").capitalize(),
            "lastActive": "2026-08-20" if u.get("status") == "active" else "2026-07-01",
        }
        for u in USERS
    ]


@router.put("/admin/users/{user_id}")
def update_admin_user(user_id: int, body: UserStatusUpdate):
    target = next((u for u in USERS if u["id"] == user_id), None)
    if not target:
        raise HTTPException(status_code=404, detail=f"User {user_id} not found")
    if body.status:
        target["status"] = body.status.lower()
    if body.role:
        target["role"] = body.role
        
    logs = _load_audit_logs()
    logs.insert(0, {
        "id": len(logs) + 1,
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M"),
        "user": "Program Administrator",
        "action": "Modified User Account",
        "details": f"Updated {target['name']}: status={target['status']}, role={target['role']}",
        "category": "Security",
    })
    _save_audit_logs(logs[:50])
    return {
        "id": target["id"],
        "name": target["name"],
        "email": target["email"],
        "role": target["role"],
        "role_label": ROLE_LABELS.get(target["role"], target["role"]),
        "status": target["status"].capitalize(),
    }


@router.get("/admin/audit-logs")
def get_audit_logs():
    return _load_audit_logs()


@router.post("/admin/audit-logs")
def create_audit_log(body: AuditLogCreate):
    logs = _load_audit_logs()
    new_log = {
        "id": len(logs) + 1,
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M"),
        "user": body.user,
        "action": body.action,
        "details": body.details,
        "category": body.category,
    }
    logs.insert(0, new_log)
    _save_audit_logs(logs[:50])
    return new_log


# ==============================================================
# NOTIFICATIONS ENDPOINTS
# ==============================================================

@router.get("/notifications")
def get_notifications(role: Optional[str] = Query(None)):
    """Retrieve notifications filtered for current user role."""
    all_notifs = _load_notifications()
    if role:
        target = role.lower()
        filtered = [
            n for n in all_notifs 
            if n.get("recipient_role", "").lower() == target or n.get("recipient_role") == "all"
            or (target in ["program_manager", "leadership"] and n.get("recipient_role") in ["program_manager", "leadership"])
        ]
    else:
        filtered = all_notifs

    unread_count = sum(1 for n in filtered if not n.get("read", False))
    return {
        "notifications": filtered,
        "unread_count": unread_count,
        "total": len(filtered)
    }


@router.post("/notifications/{notification_id}/read")
def mark_notification_read(notification_id: int):
    """Mark a notification as read."""
    notifications = _load_notifications()
    for n in notifications:
        if n["id"] == notification_id:
            n["read"] = True
            break
    _save_notifications(notifications)
    return {"status": "success", "id": notification_id}


@router.post("/notifications/clear-all")
def clear_all_notifications(role: Optional[str] = Query(None)):
    """Mark all notifications as read."""
    notifications = _load_notifications()
    for n in notifications:
        if not role or n.get("recipient_role", "").lower() == role.lower() or role.lower() == "all":
            n["read"] = True
    _save_notifications(notifications)
    return {"status": "success"}
